# Configure variables for this example and build using generic makefile

APP_NAME           = ExecExtProc
APP_FORM           = ExecExtProcForm
XL                 = 0
ENGINE             = 1

include make.dotnet

